openapi: 3.0.1
info:
  title: Product Service API
  description: API documentation for Product Service API.
  version: 1.0.0

servers:
  - url: https://ettdobdt61.execute-api.eu-central-1.amazonaws.com/prod/
    description: API Gateway

paths:
  /products:
    get:
      summary: Get all products
      description: Retrieves a list of products from the AWS Lambda function.
      responses:
        "200":
          description: Successfully retrieved products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1"
                    title:
                      type: string
                      example: "Product 1"
                    price:
                      type: number
                      example: "100"
                    description:
                      type: string
                      example: "Product 1 description"
        "500":
          description: Error fetching products
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."
    post:
      summary: Add new product
      description: Adds new product.
      requestBody:
        description: realTimePaymentRequest
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Successfully retrieved products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1"
                    title:
                      type: string
                      example: "Product 1"
                    price:
                      type: number
                      example: "100"
                    description:
                      type: string
                      example: "Product 1 description"
        "400":
          description: Error fetching products
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid product data."
        "409":
          description: Error fetching products
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Transaction failed. Product might already exist."
        "500":
          description: Error fetching products
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."
  /products/{productId}:
    get:
      summary: Get product by ID
      description: Retrieves a product by ID from the AWS Lambda function.
      parameters:
        - name: productId
          in: path
          required: true
          description: productId
          schema:
            type: string
            example: "1"
      responses:
        "200":
          description: Successfully retrieved product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  title:
                    type: string
                    example: "Product 1"
                  price:
                    type: number
                    example: "100"
                  description:
                    type: string
                    example: "Product 1 description"
        "400":
          description: Product ID is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product ID is required"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product not found"
        "500":
          description: Error fetching products
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."
components:
  schemas:
    Product:
      properties:
        title:
          type: string
          example: "Product 1"
        price:
          type: number
          example: "100"
        description:
          type: string
          example: "Product 1 description"
        count:
          type: number
          example: "1"
